# conda env create -f environment.yml
# conda activate MLenv

name: MLenv
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy=2.1.3
  - pandas=2.2.3
  - matplotlib=3.10.0
  - scikit-learn=1.7.0
  - openpyxl=3.1.5